/**
 * 消费统计界面组件
 * @author fanyerong
 */
import React, {Component} from 'react';
import '../../UI/bothpages.css'
import './ConsumptionStatistics.css'
import Window from '../../UI/Window';


export default class extends Component {   
    constructor(props) {
        super(props);           
    }; 
    render() {      
        return ( 
               <Window title='消费统计' onClose={this.props.closeView}>                  
                        <div className="bothpages_list">
                            <div>累计订单数 :<b>256485</b></div>
                            <div>累计订单总额 :<b>123456485元</b></div>
                        </div>
                        <div className="bothpages_count">                           
                              <div className="bothpages_count_title">
                                 <span></span>
                                 <span>会员手机号</span>
                                 <span>交易单号</span>
                                 <span>时间</span>
                                 <span>金额</span>
                               </div>                                                     
                            <table className="bothpages_count_list" cellPadding="0" cellSpacing="0" border="0">  
                                <tbody>                            
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>

                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr><tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>

                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                    <tr>
                                        <td>1</td>
                                        <td>12584521585</td>
                                        <td>23456987</td>
                                        <td>1254875236</td>
                                        <td>1258963541</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>                          
                      
                </Window> 
        );            
    };
}






