/**
 * 前台情况界面
 * @author fanyerong
 */
import React, {Component} from 'react';
import Window from '../../UI/Window';
import './ForegroundStatistics.css';

export default class extends Component {   
    constructor(props) {
        super(props);           
    }; 
    render() {
        return (             
            <Window title='前台情况' onClose={this.props.closeView}>   
                <div className="ope-inc-head for-sta-head">
                    <a>统计时间：2018-06-21 22：00：57 至2018-06-22 19：00：00</a>
                    <a>衣物件数：10件</a>
                </div>
                <div class="Succession-name ReportLossQuery">已为您找到：<b>25</b>条记录</div>
                <table className='ui-table-base for-sta-tab'>
                    <thead>
                        <tr>
                            <td>流水号</td>
                            <td>店员姓名</td>
                            <td>衣物件数</td>
                            <td>金额</td>
                            <td>实收金额</td>
                            <td>折扣率</td>
                            <td>收款类型</td>
                            <td>客户电话</td>
                            <td>客户姓名</td>
                            <td>时间</td>
                            <td>充值卡号</td>
                            <td>卡类型</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                        <tr>
                            <td>211222</td>
                            <td>冉冲</td>
                            <td>3</td>
                            <td>100</td>
                            <td>98</td>
                            <td>98折</td>
                            <td>现金</td>
                            <td>15820282872</td>
                            <td>小范</td>
                            <td>2018-6-24</td>
                            <td>7282828282</td>
                            <td>金卡</td>
                        </tr>
                    </tbody>
                </table>
             </Window> 
        );
    }
}