/**
 * 会员消费查询页面
 * @author  fanyerong
 */
import React, { Component } from 'react';
import Window from '../../UI/Window';
import './Membershipquery.css';
import './Membersdetail.css';

export default class extends Component {
    constructor(props) {
        super(props); 
        this.state = {show:false}               
    };  
    render() {               
        return (       
            <div>
            <Window title='会员消费查询' onClose={this.props.closeView}>
                <div className="change_card_date">
                    <div className="change_card_date_left">
                        <div>卡号：<input type="text"  /></div>
                        <div>姓名：<input type="text"  /></div>
                        <div>手机号：<input type="text" /></div>
                    </div>
                    <button type='button' className='e-btn chaxun' >查询</button>
                    <button type='button' className='e-btn chaxun' >读卡</button>
                </div>
                {/* 表格部分 欠费衣物信息*/}
                <p className='change_card_result_title'>已找到<a>5248</a>条结果</p>
                <table className='change_card_table'>
                    <thead>
                        <tr>
                            <td></td>
                            <td>卡号</td>
                            <td>姓名</td>
                            <td>手机号</td>
                            <td>卡类型</td>
                            <td>余额</td>
                            <td>操作</td>
                        </tr>
                    </thead>
                    <tbody>
                       <tr>
                           <td></td>
                           <td>55555</td>
                           <td>王八蛋</td>
                           <td>1888888888888</td>
                           <td>平台</td>
                           <td>25487</td>
                           <td onClick={e => this.setState({show:true})}>查看详情</td>
                       </tr>
                    </tbody>
                </table>                  
            </Window> 
            {
                this.state.show
                &&
                <Window title='会员消费查询详情' onClose={this.props.closeView}>
                   <div className="Membersdetail">
                      <div>卡号：<span>158475254582</span></div>
                      <div>姓名：<span>旺旺旺</span></div>
                      <div>手机号：<span>158475254582</span></div>
                      <div>卡类型：<span>平台会员卡</span></div>
                      <div>余额：<span>158475254582</span></div>                  
                   </div> 
                   <div className="Membersdetail-tab">
                      <div className="Membersdetail-tab-title">已为您找到<span>25485</span>条记录</div>
                      <table>
                          <thead>
                              <tr>
                                  <th></th>
                                  <th>流水号</th>
                                  <th>店铺ID</th>
                                  <th>店员姓名</th>
                                  <th>衣物件数</th>
                                  <th>金额</th>
                                  <th>实收金额</th>
                                  <th>折扣率 </th>
                                  <th>收银类型</th>
                                  <th>日期</th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>

                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td>4555584751</td>
                                  <td>45</td>
                                  <td>旺旺旺</td>
                                  <td>43</td>
                                  <td>564</td>
                                  <td>455</td>
                                  <td>56%</td>
                                  <td>3245</td>
                                  <td>2015-05-23</td>
                              </tr>
                          </tbody>
                      </table>
                   </div>                              
                </Window>
            }          
        </div>    
        );
    }
}