/**
 * 衣服界面
 * @author  fanyerong
 */
import React, { Component } from 'react';
export default class extends Component {
    constructor(props) {
        super(props);  
                    
    };  
    render() {               
        return (       
                    <div className="commoditysales-footerdiv-left">
                      <table>
                          <thead>
                              <tr>
                                  <th>商品编号</th>
                                  <th>商品名称</th>
                                  <th>折扣率</th>
                                  <th>库存</th>
                                  <th>单价</th>                                                                 
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr><tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>

                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr><tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                              <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>                                 
                                  <td></td>
                              </tr>
                          </tbody>
                      </table>
                   </div>   
        );
    }
}

