/**
 * 经营明细界面组件
 * @author fanyerong
 */
import React, {Component} from 'react';
import Window from '../../UI/Window';
import Select from '../../UI/Select';
import './OperatingDetails.css';

export default class extends Component {   
    constructor(props) {
        super(props);           
    }; 
    render() {
      
        return (             
            <Window title='经营明细' onClose={this.props.closeView}>
                 <div className="Succession_data">
                            <div className="Succession_dataLeft managerquery_dataLeft">
                                <div>操作员：<Select option={['支付宝','微信','现金']} selected='现金'  onChange={value => console.log(value)}/></div>                           
                                <div>结束日期：<input type="date" /></div>
                                <div>结束日期：<input type="date" /></div>
                            </div>
                            <button className="e-btn managerquery_btn">查询</button> 
                </div>  
                <div className="Takeclothes-div-title">已为您找到<b>4535</b>条数据</div>
                    <div className="Takeclothes-tab Takeclothesdetail-tab">
                        <table cellPadding="0" cellSpacing="0" border="0">
                           <thead>
                               <tr>
                                   <th></th>
                                   <th>流水号</th>
                                   <th>店员姓名</th>
                                   <th>衣物件数</th>
                                   <th>金额</th>
                                   <th>实收金额</th>
                                   <th>折扣率</th>
                                   <th>收款类型</th>
                                   <th>客户电话</th>
                                   <th>客户姓名</th>
                                   <th>时间</th>
                               </tr>
                           </thead>
                           <tbody>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr><tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr><tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr><tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               <tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr><tr>
                                   <td></td>
                                   <td>45547586586</td>
                                   <td>吱吱</td>
                                   <td>13546079987</td>
                                   <td>154852456321</td>
                                   <td>25</td>
                                   <td>￥25.00</td>
                                   <td>￥45.10</td>                                  
                                   <td>6/13</td> 
                                   <td>6/13</td>
                                   <td>6/13</td>                                  
                               </tr>
                               
                               
                           </tbody>
                        </table> 
                    </div>                   
                    <div className="bothpages-footer">
                            <div className="bothpages-footer-btn">
                                    <span>首页</span>
                                    <span>上一页</span>
                                    <span>下一页</span>
                                    <span>尾页</span>
                            </div>
                            <div className="bothpages-footer-all">第<span>1</span>页/共<span>4</span>页</div>
                            <div className="bothpages-footer-both">每页<span>20</span>条，共<span>112</span>条</div>
                    </div>  
                      
            </Window>  
        );
    }
}