/**
 * 衣物统计界面组件
 * @author fanyerong
 */
import React, {Component} from 'react';
import Window from '../../UI/Window';
import './Clothestat.css';

export default class extends Component {   
    constructor(props) {
        super(props);           
    };   
    render() {
       var arr = ['查询','打印','退出'].map((item,index) =><button key={index} data-index={index} onClick={this.arrbutton}>{item}</button>);
       return (             
            <Window title='衣物统计' onClose={this.props.closeView}>   
                      <div className="revokedata_data">
                         <div className="revokedata_dataLeft">
                            <div>开始日期：<input type="date"  /></div>                           
                            <div>结束日期：<input type="date" /></div>
                         </div>
                         <div className="revokedata_dataright">
                           {arr}
                         </div>
                         <div className="vipstats-detail"><input type="checkbox" />明细</div>
                      </div>
                      <div className="clothall">类别合计</div>
                        <table className="clothall-tab">
                          <thead>
                              <tr>
                                  <th>衣物类别</th>
                                  <th>数量</th>
                              </tr>
                          </thead>
                          <tbody>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr><tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>

                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr><tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>

                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr><tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                              <tr>
                                  <td>外套</td>
                                  <td>440</td>
                              </tr>
                          </tbody>
                        </table>  
                      
                      
                      <div className="revokedata_list revokedata_last clothestat-tab">
                        <div>衣物明细<b>共有 <a>25487</a> 条</b><span className="revokedata_prompt"></span></div>
                        <table>
                               <thead>
                                   <tr>
                                       <th></th>
                                       <th>店员姓名</th>
                                       <th>客户电话</th>
                                       <th>流水号</th>
                                       <th>水洗条码号</th>
                                       <th>衣物编码</th>
                                       <th>衣物名称</th>
                                       <th>衣物颜色</th>
                                       <th>衣物网格</th>
                                       <th>衣物处理</th>
                                       <th>价格</th>
                                       <th>品牌</th>
                                       <th>折后价格</th>
                                       <th>备注</th>
                                       <th>状态</th>
                                       <th>日期</th>
                                       <th>时间</th>
                                       <th>交货定期</th>
                                       <th>交货日期</th>
                                       <th>格架号</th>
                                       <th>是否上传</th>
                                       <th>附加服务</th>
                                       <th>附加费</th>
                                       <th>洗后效果</th>
                                       <th>衣物件数</th>
                                       <th>客户姓名</th>
                                       <th>充值卡号</th>
                                       <th>卡类型</th>
                                       <th>单位</th>
                                       <th>是否打印</th>
                                       <th>住址</th>
                                       <th>包号</th>
                                       <th>类别</th>
                                       <th>折扣率</th>
                                       <th>是否返工</th>
                                       <th>联盟卡</th>
                                   </tr>                                  
                               </thead>
                               <tbody> 
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>                                  
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                               </tbody>
                           </table>                       
                      </div>
             </Window> 
        );
    }
}