/**
 * 交期预警
 * @author  fanyerong
 */
import React, { Component } from 'react';
import Window from '../../UI/Window';
import Deliverywarning from './Deliverywarning.css';

export default class extends Component {
    constructor(props) {
        super(props);
    };
    render() {
        return (
            <Window title='交期预警' onClose={this.props.closeView} >
               <div className="Deliverywarning-title">
                  <span>衣物编码:</span><input type="text" /> <button className="e-btn">查询</button>
               </div>
               <div className="deliverywarning-tab">
                  <table>
                      <thead>
                          <tr>
                              <th>衣物编码</th>
                              <th>名称</th>
                              <th>颜色</th>
                              <th>过期天数</th>
                              <th>姓名</th>
                              <th>卡号</th>
                              <th>电话</th>
                          </tr>
                      </thead>
                      <tbody>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>

                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>

                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr><tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>

                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr><tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                          <tr>
                              <td>876545</td>
                              <td>裤子</td>
                              <td>红色，白色蓝色，青色，橙色</td>
                              <td>5</td>
                              <td>旺旺</td>
                              <td>8765455663325323</td>
                              <td>18310963932</td>
                          </tr>
                      </tbody>
                  </table>
               </div>
               <div className="bothpages-footer">
                    <div className="bothpages-footer-btn">
                        <span>首页</span>
                        <span>上一页</span>
                        <span>下一页</span>
                        <span>尾页</span>
                    </div>
                    <div className="bothpages-footer-all">第<span>一</span>页/共<span>四</span>页</div>
                    <div className="bothpages-footer-both">每页<span>20</span>条，共<span>112</span>条</div>
                </div>
            </Window>
           
        );
    }
}
